const fallback = require('express-history-api-fallback')
const path = require('path')
const express = require('express')
const app = express()
app.disable('x-powered-by')
const root = path.join(__dirname, '/dist')
app.use(express.static(root))
app.use(fallback('index.html', { root }))
app.listen(process.env.PORT || 3000, () => {
  console.log('Project running...')
})
